package ru.stqa.pft.addressbook;// Generated by Selenium IDE
import org.junit.Test;


public class GroupDeletionTestsTest extends TestBase{

  @Test
  public void groupDeletionTests() {
    goToGroupPage();
    selectGroup();
    deleteSelectedGroups();
    returnToGroupPage();
  }

}
