package ru.stqa.pft.addressbook;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;


public class TestaddressTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:/Users/Vlad20/Desktop/chrome_driver/chromedriver.exe");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    driver.get("http://addressbook/");
    driver.manage().window().setSize(new Dimension(1055, 824));
    login("user", "admin", "pass", "secret", By.cssSelector("input:nth-child(7)"));
  }

  private void login(String user, String admin, String pass, String secret, By by) {
    driver.findElement(By.name(user)).click();
    driver.findElement(By.name(user)).sendKeys(admin);
    driver.findElement(By.name(pass)).click();
    driver.findElement(By.name(pass)).sendKeys(secret);
    driver.findElement(by).click();
  }

  @Test
  public void testaddress() {
    goToGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("1", "2", "3"));
    submitGroupCreation();
    returnToGroupPage();
  }

  private void returnToGroupPage() {
    driver.findElement(By.linkText("group page")).click();
  }

  private void submitGroupCreation() {
    driver.findElement(By.name("submit")).click();
  }

  private void fillGroupForm(GroupData groupData) {
    driver.findElement(By.name("group_name")).click();
    driver.findElement(By.name("group_name")).sendKeys(groupData.getName());
    driver.findElement(By.name("group_header")).click();
    driver.findElement(By.name("group_header")).sendKeys(groupData.getHeader());
    driver.findElement(By.name("group_footer")).click();
    driver.findElement(By.name("group_footer")).sendKeys(groupData.getFooter());
  }

  private void initGroupCreation() {
    driver.findElement(By.name("new")).click();
  }

  private void goToGroupPage() {
    driver.findElement(By.xpath("//a[contains(@href, \'group.php\')]")).click();
  }


  @After
  public void tearDown() {
    driver.quit();
  }
}
