package ru.stqa.pft.addressbook;// Generated by Selenium IDE
import org.junit.Test;


public class TestaddressTest extends TestBase{

    @Test
  public void testaddress() {
    goToGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("1", "2", "3"));
    submitGroupCreation();
    returnToGroupPage();
  }


}
