package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;
import ru.stqa.pft.addressbook.model.ContactData;


public class ContactCreationTests extends TestBase {

    @Test
    public void contactCreationTests() {
        app.getNavigationHelper().goToContactCreation();
        app.getContactHelper().initContactCreation();
        app.getContactHelper().fillContactForm(new ContactData("Vlad", "Vlasov"));
        app.getContactHelper().submitContactCreation();
    }

}
