package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.ContactData;

import java.io.File;


public class ContactCreationTests extends TestBase {

    @Test
    public void contactCreationTests() {
        app.goTo().goToContactCreation();
        app.contact().initContactCreation();
        File photo = new File(getClass().getClassLoader().getResource("img1.jpg").getFile());
        app.contact().fillContactForm(
                new ContactData().withFirstname("test_name").withLastname("test_surname").withPhoto(photo), true);
        app.contact().submitContactCreation();
    }

}
